### ISSUE TITLE
Doesn't work with Redmine 4.1.0

### ISSUE THREAD

**Issue by kou** [suer/redmine_emoji#6]
It seems that we can't use `Rails.configuration.assets` in `init.rb` with Redmine 4.1.0:

```console
% sudo -u redmine -H env RAILS_ENV=production bin/rails console
Traceback (most recent call last):
	45: from bin/rails:4:in `<main>'
	44: from bin/rails:4:in `require'
	43: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
	42: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/command.rb:46:in `invoke'
	41: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/command/base.rb:69:in `perform'
	40: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	39: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	38: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	37: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/commands/console/console_command.rb:95:in `perform'
	36: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	35: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/command/actions.rb:28:in `require_environment!'
	34: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
	33: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
	32: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	31: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
	30: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
	29: from /home/redmine/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
	28: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
	27: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
	26: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	25: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	24: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	23: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
	22: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
	21: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	20: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	19: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	18: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	17: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	16: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
	15: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
	14: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
	13: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:89:in `prepare!'
	12: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
	11: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
	10: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
	 9: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
	 8: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
	 7: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
	 6: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
	 5: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
	 4: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	 3: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
	 2: from /home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `instance_exec'
	 1: from /home/redmine/redmine-4.1.0/plugins/redmine_emoji/init.rb:13:in `block in <top (required)>'
/home/redmine/redmine-4.1.0/vendor/bundler/ruby/2.5.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000055b93e0da118> (NoMethodError)
Did you mean?  asset_host
```

I may send a pull request later.

**Comment by suer** [comment]
Thank you for reporting!

`sprockets/railtie` is no longer loaded.
https://redmine.org/issues/32223

I think that it works well to remove following line.
https://github.com/suer/redmine_emoji/blob/0a23531/init.rb#L13

I am not very familiar with sprockets,
So I'm not sure this is right.
